---
"on":
  push:
    branches:
      - main

jobs:

  build:
    strategy:
      matrix:
        os:
          #- ubuntu-24.04-arm  # arm64
          #- ubuntu-24.04      # x86
          - macos-26          # arm64
          - macos-15          # arm64
          - macos-15-intel    # x86
          #- windows-11-arm    # arm64
          #- windows-2025      # x86
        uv-version:
          - "0.9.2"
          - "0.8.24"
          - "0.8.8"
          - "0.7.22"
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
      - uses: actions/checkout@v5.0.0
      - uses: astral-sh/setup-uv@v7.0.0
        with:
          version: ${{ matrix['uv-version'] }}
      - name: Setup venv
        run: |
          uv venv --python 3.13
      - name: Install Nuitka
        run: |
          uv pip install "nuitka @ git+https://github.com/Nuitka/Nuitka.git@factory"
      - name: nuitka --version
        run: |
          uv run -- nuitka --version
      - name: Build binary
        id: build-binary
        continue-on-error: true
        run: >
          uv run -- nuitka --onefile --assume-yes-for-downloads --output-filename=cli${{ runner.os == 'Windows' && '.exe' || '.bin' }} cli/__main__.py
      - name: Upload Nuitka crash report
        uses: actions/upload-artifact@v4.6.2
        with:
          name: nuitka-crash-report-${{ matrix.os }}.xml
          if-no-files-found: ignore
          path: nuitka-crash-report.xml
      - if: steps.build-binary.outcome == 'failure'
        run: |
          echo "Nuitka build failed, skipping the rest of the steps."
          exit 1
      - name: Install exiftool - Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt --quiet --yes install exiftool
      - name: Install exiftool - macOS
        if: runner.os == 'macOS'
        run: |
          brew install exiftool
      - name: Install exiftool - Windows
        if: runner.os == 'Windows'
        run: |
          choco install exiftool --no-progress --yes
      - name: Binary metadata
        # Ubuntu:
        #   CPU Type      : Arm 64-bits (Armv8/AArch64)
        #   CPU Type      : AMD x86-64
        # macOS:
        #   CPU Type      : ARM 64-bit
        #   CPU Type      : x86 64-bit
        # Windows
        #   Machine Type  : ARM64 little endian
        #   Machine Type  : AMD AMD64
        run: |
          exiftool${{ runner.os == 'Windows' && '.exe' || '' }} cli${{ runner.os == 'Windows' && '.exe' || '.bin' }}
      - name: Set binary permissions
        if: runner.os != 'Windows'
        run: |
          chmod +x cli.bin
      - name: Run binary
        run: |
          ${{ runner.os == 'Windows' && '.\cli.exe' || './cli.bin' }}